name: Release
on:
  push:
    branches:
    - master
    # tags:
    #   - 'v*'
  # pull_request:
  # release:
  #   types: [created]
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "Yes" to confirm deploy'     
        required: true
        default: 'No'

defaults:
  run:
    working-directory: backend

jobs:
  publish:
    name: 'Publish release'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
